// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.service;

import com.polypharm.gescom.domain.Agence;
import com.polypharm.gescom.service.AgenceService;
import java.util.List;

privileged aspect AgenceService_Roo_Service {
    
    public abstract long AgenceService.countAllAgences();    
    public abstract void AgenceService.deleteAgence(Agence agence);    
    public abstract Agence AgenceService.findAgence(Long id);    
    public abstract List<Agence> AgenceService.findAllAgences();    
    public abstract List<Agence> AgenceService.findAgenceEntries(int firstResult, int maxResults);    
    public abstract void AgenceService.saveAgence(Agence agence);    
    public abstract Agence AgenceService.updateAgence(Agence agence);    
}
