// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.service;

import com.polypharm.gescom.domain.Agence;
import com.polypharm.gescom.repository.AgenceRepository;
import com.polypharm.gescom.service.AgenceServiceImpl;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AgenceServiceImpl_Roo_Service {
    
    declare @type: AgenceServiceImpl: @Service;
    
    declare @type: AgenceServiceImpl: @Transactional;
    
    @Autowired
    AgenceRepository AgenceServiceImpl.agenceRepository;
    
    public long AgenceServiceImpl.countAllAgences() {
        return agenceRepository.count();
    }
    
    public void AgenceServiceImpl.deleteAgence(Agence agence) {
        agenceRepository.delete(agence);
    }
    
    public Agence AgenceServiceImpl.findAgence(Long id) {
        return agenceRepository.findOne(id);
    }
    
    public List<Agence> AgenceServiceImpl.findAllAgences() {
        return agenceRepository.findAll();
    }
    
    public List<Agence> AgenceServiceImpl.findAgenceEntries(int firstResult, int maxResults) {
        return agenceRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
    }
    
    public void AgenceServiceImpl.saveAgence(Agence agence) {
        agenceRepository.save(agence);
    }
    
    public Agence AgenceServiceImpl.updateAgence(Agence agence) {
        return agenceRepository.save(agence);
    }
    
}
