// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.service;

import com.polypharm.gescom.domain.AssistanceCommerciale;
import com.polypharm.gescom.service.AssistanceCommercialeService;
import java.util.List;

privileged aspect AssistanceCommercialeService_Roo_Service {
    
    public abstract long AssistanceCommercialeService.countAllAssistanceCommerciales();    
    public abstract void AssistanceCommercialeService.deleteAssistanceCommerciale(AssistanceCommerciale assistanceCommerciale);    
    public abstract AssistanceCommerciale AssistanceCommercialeService.findAssistanceCommerciale(Long id);    
    public abstract List<AssistanceCommerciale> AssistanceCommercialeService.findAllAssistanceCommerciales();    
    public abstract List<AssistanceCommerciale> AssistanceCommercialeService.findAssistanceCommercialeEntries(int firstResult, int maxResults);    
    public abstract void AssistanceCommercialeService.saveAssistanceCommerciale(AssistanceCommerciale assistanceCommerciale);    
    public abstract AssistanceCommerciale AssistanceCommercialeService.updateAssistanceCommerciale(AssistanceCommerciale assistanceCommerciale);    
}
