// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.service;

import com.polypharm.gescom.domain.AssistanceCommerciale;
import com.polypharm.gescom.repository.AssistanceCommercialeRepository;
import com.polypharm.gescom.service.AssistanceCommercialeServiceImpl;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AssistanceCommercialeServiceImpl_Roo_Service {
    
    declare @type: AssistanceCommercialeServiceImpl: @Service;
    
    declare @type: AssistanceCommercialeServiceImpl: @Transactional;
    
    @Autowired
    AssistanceCommercialeRepository AssistanceCommercialeServiceImpl.assistanceCommercialeRepository;
    
    public long AssistanceCommercialeServiceImpl.countAllAssistanceCommerciales() {
        return assistanceCommercialeRepository.count();
    }
    
    public void AssistanceCommercialeServiceImpl.deleteAssistanceCommerciale(AssistanceCommerciale assistanceCommerciale) {
        assistanceCommercialeRepository.delete(assistanceCommerciale);
    }
    
    public AssistanceCommerciale AssistanceCommercialeServiceImpl.findAssistanceCommerciale(Long id) {
        return assistanceCommercialeRepository.findOne(id);
    }
    
    public List<AssistanceCommerciale> AssistanceCommercialeServiceImpl.findAllAssistanceCommerciales() {
        return assistanceCommercialeRepository.findAll();
    }
    
    public List<AssistanceCommerciale> AssistanceCommercialeServiceImpl.findAssistanceCommercialeEntries(int firstResult, int maxResults) {
        return assistanceCommercialeRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
    }
    
    public void AssistanceCommercialeServiceImpl.saveAssistanceCommerciale(AssistanceCommerciale assistanceCommerciale) {
        assistanceCommercialeRepository.save(assistanceCommerciale);
    }
    
    public AssistanceCommerciale AssistanceCommercialeServiceImpl.updateAssistanceCommerciale(AssistanceCommerciale assistanceCommerciale) {
        return assistanceCommercialeRepository.save(assistanceCommerciale);
    }
    
}
