// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.service;

import com.polypharm.gescom.domain.AutoFormationEntreprise;
import com.polypharm.gescom.repository.AutoFormationEntrepriseRepository;
import com.polypharm.gescom.service.AutoFormationEntrepriseServiceImpl;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AutoFormationEntrepriseServiceImpl_Roo_Service {
    
    declare @type: AutoFormationEntrepriseServiceImpl: @Service;
    
    declare @type: AutoFormationEntrepriseServiceImpl: @Transactional;
    
    @Autowired
    AutoFormationEntrepriseRepository AutoFormationEntrepriseServiceImpl.autoFormationEntrepriseRepository;
    
    public long AutoFormationEntrepriseServiceImpl.countAllAutoFormationEntreprises() {
        return autoFormationEntrepriseRepository.count();
    }
    
    public void AutoFormationEntrepriseServiceImpl.deleteAutoFormationEntreprise(AutoFormationEntreprise autoFormationEntreprise) {
        autoFormationEntrepriseRepository.delete(autoFormationEntreprise);
    }
    
    public AutoFormationEntreprise AutoFormationEntrepriseServiceImpl.findAutoFormationEntreprise(Long id) {
        return autoFormationEntrepriseRepository.findOne(id);
    }
    
    public List<AutoFormationEntreprise> AutoFormationEntrepriseServiceImpl.findAllAutoFormationEntreprises() {
        return autoFormationEntrepriseRepository.findAll();
    }
    
    public List<AutoFormationEntreprise> AutoFormationEntrepriseServiceImpl.findAutoFormationEntrepriseEntries(int firstResult, int maxResults) {
        return autoFormationEntrepriseRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
    }
    
    public void AutoFormationEntrepriseServiceImpl.saveAutoFormationEntreprise(AutoFormationEntreprise autoFormationEntreprise) {
        autoFormationEntrepriseRepository.save(autoFormationEntreprise);
    }
    
    public AutoFormationEntreprise AutoFormationEntrepriseServiceImpl.updateAutoFormationEntreprise(AutoFormationEntreprise autoFormationEntreprise) {
        return autoFormationEntrepriseRepository.save(autoFormationEntreprise);
    }
    
}
