// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.service;

import com.polypharm.gescom.domain.AutoFormationEntreprise;
import com.polypharm.gescom.service.AutoFormationEntrepriseService;
import java.util.List;

privileged aspect AutoFormationEntrepriseService_Roo_Service {
    
    public abstract long AutoFormationEntrepriseService.countAllAutoFormationEntreprises();    
    public abstract void AutoFormationEntrepriseService.deleteAutoFormationEntreprise(AutoFormationEntreprise autoFormationEntreprise);    
    public abstract AutoFormationEntreprise AutoFormationEntrepriseService.findAutoFormationEntreprise(Long id);    
    public abstract List<AutoFormationEntreprise> AutoFormationEntrepriseService.findAllAutoFormationEntreprises();    
    public abstract List<AutoFormationEntreprise> AutoFormationEntrepriseService.findAutoFormationEntrepriseEntries(int firstResult, int maxResults);    
    public abstract void AutoFormationEntrepriseService.saveAutoFormationEntreprise(AutoFormationEntreprise autoFormationEntreprise);    
    public abstract AutoFormationEntreprise AutoFormationEntrepriseService.updateAutoFormationEntreprise(AutoFormationEntreprise autoFormationEntreprise);    
}
