// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.service;

import com.polypharm.gescom.domain.ConseilClient;
import com.polypharm.gescom.service.ConseilClientService;
import java.util.List;

privileged aspect ConseilClientService_Roo_Service {
    
    public abstract long ConseilClientService.countAllConseilClients();    
    public abstract void ConseilClientService.deleteConseilClient(ConseilClient conseilClient);    
    public abstract ConseilClient ConseilClientService.findConseilClient(Long id);    
    public abstract List<ConseilClient> ConseilClientService.findAllConseilClients();    
    public abstract List<ConseilClient> ConseilClientService.findConseilClientEntries(int firstResult, int maxResults);    
    public abstract void ConseilClientService.saveConseilClient(ConseilClient conseilClient);    
    public abstract ConseilClient ConseilClientService.updateConseilClient(ConseilClient conseilClient);    
}
