// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.service;

import com.polypharm.gescom.domain.ConseilClient;
import com.polypharm.gescom.repository.ConseilClientRepository;
import com.polypharm.gescom.service.ConseilClientServiceImpl;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ConseilClientServiceImpl_Roo_Service {
    
    declare @type: ConseilClientServiceImpl: @Service;
    
    declare @type: ConseilClientServiceImpl: @Transactional;
    
    @Autowired
    ConseilClientRepository ConseilClientServiceImpl.conseilClientRepository;
    
    public long ConseilClientServiceImpl.countAllConseilClients() {
        return conseilClientRepository.count();
    }
    
    public void ConseilClientServiceImpl.deleteConseilClient(ConseilClient conseilClient) {
        conseilClientRepository.delete(conseilClient);
    }
    
    public ConseilClient ConseilClientServiceImpl.findConseilClient(Long id) {
        return conseilClientRepository.findOne(id);
    }
    
    public List<ConseilClient> ConseilClientServiceImpl.findAllConseilClients() {
        return conseilClientRepository.findAll();
    }
    
    public List<ConseilClient> ConseilClientServiceImpl.findConseilClientEntries(int firstResult, int maxResults) {
        return conseilClientRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
    }
    
    public void ConseilClientServiceImpl.saveConseilClient(ConseilClient conseilClient) {
        conseilClientRepository.save(conseilClient);
    }
    
    public ConseilClient ConseilClientServiceImpl.updateConseilClient(ConseilClient conseilClient) {
        return conseilClientRepository.save(conseilClient);
    }
    
}
