// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.service;

import com.polypharm.gescom.domain.DossierCreance;
import com.polypharm.gescom.repository.DossierCreanceRepository;
import com.polypharm.gescom.service.DossierCreanceServiceImpl;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DossierCreanceServiceImpl_Roo_Service {
    
    declare @type: DossierCreanceServiceImpl: @Service;
    
    declare @type: DossierCreanceServiceImpl: @Transactional;
    
    @Autowired
    DossierCreanceRepository DossierCreanceServiceImpl.dossierCreanceRepository;
    
    public long DossierCreanceServiceImpl.countAllDossierCreances() {
        return dossierCreanceRepository.count();
    }
    
    public void DossierCreanceServiceImpl.deleteDossierCreance(DossierCreance dossierCreance) {
        dossierCreanceRepository.delete(dossierCreance);
    }
    
    public DossierCreance DossierCreanceServiceImpl.findDossierCreance(Long id) {
        return dossierCreanceRepository.findOne(id);
    }
    
    public List<DossierCreance> DossierCreanceServiceImpl.findAllDossierCreances() {
        return dossierCreanceRepository.findAll();
    }
    
    public List<DossierCreance> DossierCreanceServiceImpl.findDossierCreanceEntries(int firstResult, int maxResults) {
        return dossierCreanceRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
    }
    
    public void DossierCreanceServiceImpl.saveDossierCreance(DossierCreance dossierCreance) {
        dossierCreanceRepository.save(dossierCreance);
    }
    
    public DossierCreance DossierCreanceServiceImpl.updateDossierCreance(DossierCreance dossierCreance) {
        return dossierCreanceRepository.save(dossierCreance);
    }
    
}
