// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.service;

import com.polypharm.gescom.domain.FamilleProduit;
import com.polypharm.gescom.service.FamilleProduitService;
import java.util.List;

privileged aspect FamilleProduitService_Roo_Service {
    
    public abstract long FamilleProduitService.countAllFamilleProduits();    
    public abstract void FamilleProduitService.deleteFamilleProduit(FamilleProduit familleProduit);    
    public abstract FamilleProduit FamilleProduitService.findFamilleProduit(Long id);    
    public abstract List<FamilleProduit> FamilleProduitService.findAllFamilleProduits();    
    public abstract List<FamilleProduit> FamilleProduitService.findFamilleProduitEntries(int firstResult, int maxResults);    
    public abstract void FamilleProduitService.saveFamilleProduit(FamilleProduit familleProduit);    
    public abstract FamilleProduit FamilleProduitService.updateFamilleProduit(FamilleProduit familleProduit);    
}
