// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.service;

import com.polypharm.gescom.domain.FamilleProduit;
import com.polypharm.gescom.repository.FamilleProduitRepository;
import com.polypharm.gescom.service.FamilleProduitServiceImpl;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FamilleProduitServiceImpl_Roo_Service {
    
    declare @type: FamilleProduitServiceImpl: @Service;
    
    declare @type: FamilleProduitServiceImpl: @Transactional;
    
    @Autowired
    FamilleProduitRepository FamilleProduitServiceImpl.familleProduitRepository;
    
    public long FamilleProduitServiceImpl.countAllFamilleProduits() {
        return familleProduitRepository.count();
    }
    
    public void FamilleProduitServiceImpl.deleteFamilleProduit(FamilleProduit familleProduit) {
        familleProduitRepository.delete(familleProduit);
    }
    
    public FamilleProduit FamilleProduitServiceImpl.findFamilleProduit(Long id) {
        return familleProduitRepository.findOne(id);
    }
    
    public List<FamilleProduit> FamilleProduitServiceImpl.findAllFamilleProduits() {
        return familleProduitRepository.findAll();
    }
    
    public List<FamilleProduit> FamilleProduitServiceImpl.findFamilleProduitEntries(int firstResult, int maxResults) {
        return familleProduitRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
    }
    
    public void FamilleProduitServiceImpl.saveFamilleProduit(FamilleProduit familleProduit) {
        familleProduitRepository.save(familleProduit);
    }
    
    public FamilleProduit FamilleProduitServiceImpl.updateFamilleProduit(FamilleProduit familleProduit) {
        return familleProduitRepository.save(familleProduit);
    }
    
}
