// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.service;

import com.polypharm.gescom.domain.FormationUtilisateur;
import com.polypharm.gescom.service.FormationUtilisateurService;
import java.util.List;

privileged aspect FormationUtilisateurService_Roo_Service {
    
    public abstract long FormationUtilisateurService.countAllFormationUtilisateurs();    
    public abstract void FormationUtilisateurService.deleteFormationUtilisateur(FormationUtilisateur formationUtilisateur);    
    public abstract FormationUtilisateur FormationUtilisateurService.findFormationUtilisateur(Long id);    
    public abstract List<FormationUtilisateur> FormationUtilisateurService.findAllFormationUtilisateurs();    
    public abstract List<FormationUtilisateur> FormationUtilisateurService.findFormationUtilisateurEntries(int firstResult, int maxResults);    
    public abstract void FormationUtilisateurService.saveFormationUtilisateur(FormationUtilisateur formationUtilisateur);    
    public abstract FormationUtilisateur FormationUtilisateurService.updateFormationUtilisateur(FormationUtilisateur formationUtilisateur);    
}
