// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.service;

import com.polypharm.gescom.domain.Installation;
import com.polypharm.gescom.service.InstallationService;
import java.util.List;

privileged aspect InstallationService_Roo_Service {
    
    public abstract long InstallationService.countAllInstallations();    
    public abstract void InstallationService.deleteInstallation(Installation installation);    
    public abstract Installation InstallationService.findInstallation(Long id);    
    public abstract List<Installation> InstallationService.findAllInstallations();    
    public abstract List<Installation> InstallationService.findInstallationEntries(int firstResult, int maxResults);    
    public abstract void InstallationService.saveInstallation(Installation installation);    
    public abstract Installation InstallationService.updateInstallation(Installation installation);    
}
