// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.service;

import com.polypharm.gescom.domain.Livraison;
import com.polypharm.gescom.repository.LivraisonRepository;
import com.polypharm.gescom.service.LivraisonServiceImpl;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect LivraisonServiceImpl_Roo_Service {
    
    declare @type: LivraisonServiceImpl: @Service;
    
    declare @type: LivraisonServiceImpl: @Transactional;
    
    @Autowired
    LivraisonRepository LivraisonServiceImpl.livraisonRepository;
    
    public long LivraisonServiceImpl.countAllLivraisons() {
        return livraisonRepository.count();
    }
    
    public void LivraisonServiceImpl.deleteLivraison(Livraison livraison) {
        livraisonRepository.delete(livraison);
    }
    
    public Livraison LivraisonServiceImpl.findLivraison(Long id) {
        return livraisonRepository.findOne(id);
    }
    
    public List<Livraison> LivraisonServiceImpl.findAllLivraisons() {
        return livraisonRepository.findAll();
    }
    
    public List<Livraison> LivraisonServiceImpl.findLivraisonEntries(int firstResult, int maxResults) {
        return livraisonRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
    }
    
    public void LivraisonServiceImpl.saveLivraison(Livraison livraison) {
        livraisonRepository.save(livraison);
    }
    
    public Livraison LivraisonServiceImpl.updateLivraison(Livraison livraison) {
        return livraisonRepository.save(livraison);
    }
    
}
