// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.service;

import com.polypharm.gescom.domain.Livraison;
import com.polypharm.gescom.service.LivraisonService;
import java.util.List;

privileged aspect LivraisonService_Roo_Service {
    
    public abstract long LivraisonService.countAllLivraisons();    
    public abstract void LivraisonService.deleteLivraison(Livraison livraison);    
    public abstract Livraison LivraisonService.findLivraison(Long id);    
    public abstract List<Livraison> LivraisonService.findAllLivraisons();    
    public abstract List<Livraison> LivraisonService.findLivraisonEntries(int firstResult, int maxResults);    
    public abstract void LivraisonService.saveLivraison(Livraison livraison);    
    public abstract Livraison LivraisonService.updateLivraison(Livraison livraison);    
}
