// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.service;

import com.polypharm.gescom.domain.Personnel;
import com.polypharm.gescom.repository.PersonnelRepository;
import com.polypharm.gescom.service.PersonnelServiceImpl;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PersonnelServiceImpl_Roo_Service {
    
    declare @type: PersonnelServiceImpl: @Service;
    
    declare @type: PersonnelServiceImpl: @Transactional;
    
    @Autowired
    PersonnelRepository PersonnelServiceImpl.personnelRepository;
    
    public long PersonnelServiceImpl.countAllPersonnels() {
        return personnelRepository.count();
    }
    
    public void PersonnelServiceImpl.deletePersonnel(Personnel personnel) {
        personnelRepository.delete(personnel);
    }
    
    public Personnel PersonnelServiceImpl.findPersonnel(Long id) {
        return personnelRepository.findOne(id);
    }
    
    public List<Personnel> PersonnelServiceImpl.findAllPersonnels() {
        return personnelRepository.findAll();
    }
    
    public List<Personnel> PersonnelServiceImpl.findPersonnelEntries(int firstResult, int maxResults) {
        return personnelRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
    }
    
    public void PersonnelServiceImpl.savePersonnel(Personnel personnel) {
        personnelRepository.save(personnel);
    }
    
    public Personnel PersonnelServiceImpl.updatePersonnel(Personnel personnel) {
        return personnelRepository.save(personnel);
    }
    
}
