// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.service;

import com.polypharm.gescom.domain.Produit;
import com.polypharm.gescom.repository.ProduitRepository;
import com.polypharm.gescom.service.ProduitServiceImpl;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProduitServiceImpl_Roo_Service {
    
    declare @type: ProduitServiceImpl: @Service;
    
    declare @type: ProduitServiceImpl: @Transactional;
    
    @Autowired
    ProduitRepository ProduitServiceImpl.produitRepository;
    
    public long ProduitServiceImpl.countAllProduits() {
        return produitRepository.count();
    }
    
    public void ProduitServiceImpl.deleteProduit(Produit produit) {
        produitRepository.delete(produit);
    }
    
    public Produit ProduitServiceImpl.findProduit(Long id) {
        return produitRepository.findOne(id);
    }
    
    public List<Produit> ProduitServiceImpl.findAllProduits() {
        return produitRepository.findAll();
    }
    
    public List<Produit> ProduitServiceImpl.findProduitEntries(int firstResult, int maxResults) {
        return produitRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
    }
    
    public void ProduitServiceImpl.saveProduit(Produit produit) {
        produitRepository.save(produit);
    }
    
    public Produit ProduitServiceImpl.updateProduit(Produit produit) {
        return produitRepository.save(produit);
    }
    
}
