// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.service;

import com.polypharm.gescom.domain.ProjetCommande;
import com.polypharm.gescom.repository.ProjetCommandeRepository;
import com.polypharm.gescom.service.ProjetCommandeServiceImpl;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProjetCommandeServiceImpl_Roo_Service {
    
    declare @type: ProjetCommandeServiceImpl: @Service;
    
    declare @type: ProjetCommandeServiceImpl: @Transactional;
    
    @Autowired
    ProjetCommandeRepository ProjetCommandeServiceImpl.projetCommandeRepository;
    
    public long ProjetCommandeServiceImpl.countAllProjetCommandes() {
        return projetCommandeRepository.count();
    }
    
    public void ProjetCommandeServiceImpl.deleteProjetCommande(ProjetCommande projetCommande) {
        projetCommandeRepository.delete(projetCommande);
    }
    
    public ProjetCommande ProjetCommandeServiceImpl.findProjetCommande(Long id) {
        return projetCommandeRepository.findOne(id);
    }
    
    public List<ProjetCommande> ProjetCommandeServiceImpl.findAllProjetCommandes() {
        return projetCommandeRepository.findAll();
    }
    
    public List<ProjetCommande> ProjetCommandeServiceImpl.findProjetCommandeEntries(int firstResult, int maxResults) {
        return projetCommandeRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
    }
    
    public void ProjetCommandeServiceImpl.saveProjetCommande(ProjetCommande projetCommande) {
        projetCommandeRepository.save(projetCommande);
    }
    
    public ProjetCommande ProjetCommandeServiceImpl.updateProjetCommande(ProjetCommande projetCommande) {
        return projetCommandeRepository.save(projetCommande);
    }
    
}
