// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.service;

import com.polypharm.gescom.domain.RecrutementProspect;
import com.polypharm.gescom.service.RecrutementProspectService;
import java.util.List;

privileged aspect RecrutementProspectService_Roo_Service {
    
    public abstract long RecrutementProspectService.countAllRecrutementProspects();    
    public abstract void RecrutementProspectService.deleteRecrutementProspect(RecrutementProspect recrutementProspect);    
    public abstract RecrutementProspect RecrutementProspectService.findRecrutementProspect(Long id);    
    public abstract List<RecrutementProspect> RecrutementProspectService.findAllRecrutementProspects();    
    public abstract List<RecrutementProspect> RecrutementProspectService.findRecrutementProspectEntries(int firstResult, int maxResults);    
    public abstract void RecrutementProspectService.saveRecrutementProspect(RecrutementProspect recrutementProspect);    
    public abstract RecrutementProspect RecrutementProspectService.updateRecrutementProspect(RecrutementProspect recrutementProspect);    
}
