// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.service;

import com.polypharm.gescom.domain.RecrutementProspect;
import com.polypharm.gescom.repository.RecrutementProspectRepository;
import com.polypharm.gescom.service.RecrutementProspectServiceImpl;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RecrutementProspectServiceImpl_Roo_Service {
    
    declare @type: RecrutementProspectServiceImpl: @Service;
    
    declare @type: RecrutementProspectServiceImpl: @Transactional;
    
    @Autowired
    RecrutementProspectRepository RecrutementProspectServiceImpl.recrutementProspectRepository;
    
    public long RecrutementProspectServiceImpl.countAllRecrutementProspects() {
        return recrutementProspectRepository.count();
    }
    
    public void RecrutementProspectServiceImpl.deleteRecrutementProspect(RecrutementProspect recrutementProspect) {
        recrutementProspectRepository.delete(recrutementProspect);
    }
    
    public RecrutementProspect RecrutementProspectServiceImpl.findRecrutementProspect(Long id) {
        return recrutementProspectRepository.findOne(id);
    }
    
    public List<RecrutementProspect> RecrutementProspectServiceImpl.findAllRecrutementProspects() {
        return recrutementProspectRepository.findAll();
    }
    
    public List<RecrutementProspect> RecrutementProspectServiceImpl.findRecrutementProspectEntries(int firstResult, int maxResults) {
        return recrutementProspectRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
    }
    
    public void RecrutementProspectServiceImpl.saveRecrutementProspect(RecrutementProspect recrutementProspect) {
        recrutementProspectRepository.save(recrutementProspect);
    }
    
    public RecrutementProspect RecrutementProspectServiceImpl.updateRecrutementProspect(RecrutementProspect recrutementProspect) {
        return recrutementProspectRepository.save(recrutementProspect);
    }
    
}
