// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.service;

import com.polypharm.gescom.domain.VCDistributeurConcurent;
import com.polypharm.gescom.service.VCDistributeurConcurentService;
import java.util.List;

privileged aspect VCDistributeurConcurentService_Roo_Service {
    
    public abstract long VCDistributeurConcurentService.countAllVCDistributeurConcurents();    
    public abstract void VCDistributeurConcurentService.deleteVCDistributeurConcurent(VCDistributeurConcurent VCDistributeurConcurent_);    
    public abstract VCDistributeurConcurent VCDistributeurConcurentService.findVCDistributeurConcurent(Long id);    
    public abstract List<VCDistributeurConcurent> VCDistributeurConcurentService.findAllVCDistributeurConcurents();    
    public abstract List<VCDistributeurConcurent> VCDistributeurConcurentService.findVCDistributeurConcurentEntries(int firstResult, int maxResults);    
    public abstract void VCDistributeurConcurentService.saveVCDistributeurConcurent(VCDistributeurConcurent VCDistributeurConcurent_);    
    public abstract VCDistributeurConcurent VCDistributeurConcurentService.updateVCDistributeurConcurent(VCDistributeurConcurent VCDistributeurConcurent_);    
}
