// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.service;

import com.polypharm.gescom.domain.VeilleConcurrentielleProduit;
import com.polypharm.gescom.service.VeilleConcurrentielleProduitService;
import java.util.List;

privileged aspect VeilleConcurrentielleProduitService_Roo_Service {
    
    public abstract long VeilleConcurrentielleProduitService.countAllVeilleConcurrentielleProduits();    
    public abstract void VeilleConcurrentielleProduitService.deleteVeilleConcurrentielleProduit(VeilleConcurrentielleProduit veilleConcurrentielleProduit);    
    public abstract VeilleConcurrentielleProduit VeilleConcurrentielleProduitService.findVeilleConcurrentielleProduit(Long id);    
    public abstract List<VeilleConcurrentielleProduit> VeilleConcurrentielleProduitService.findAllVeilleConcurrentielleProduits();    
    public abstract List<VeilleConcurrentielleProduit> VeilleConcurrentielleProduitService.findVeilleConcurrentielleProduitEntries(int firstResult, int maxResults);    
    public abstract void VeilleConcurrentielleProduitService.saveVeilleConcurrentielleProduit(VeilleConcurrentielleProduit veilleConcurrentielleProduit);    
    public abstract VeilleConcurrentielleProduit VeilleConcurrentielleProduitService.updateVeilleConcurrentielleProduit(VeilleConcurrentielleProduit veilleConcurrentielleProduit);    
}
