// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.service;

import com.polypharm.gescom.domain.VulgarisationProduit;
import com.polypharm.gescom.service.VulgarisationProduitService;
import java.util.List;

privileged aspect VulgarisationProduitService_Roo_Service {
    
    public abstract long VulgarisationProduitService.countAllVulgarisationProduits();    
    public abstract void VulgarisationProduitService.deleteVulgarisationProduit(VulgarisationProduit vulgarisationProduit);    
    public abstract VulgarisationProduit VulgarisationProduitService.findVulgarisationProduit(Long id);    
    public abstract List<VulgarisationProduit> VulgarisationProduitService.findAllVulgarisationProduits();    
    public abstract List<VulgarisationProduit> VulgarisationProduitService.findVulgarisationProduitEntries(int firstResult, int maxResults);    
    public abstract void VulgarisationProduitService.saveVulgarisationProduit(VulgarisationProduit vulgarisationProduit);    
    public abstract VulgarisationProduit VulgarisationProduitService.updateVulgarisationProduit(VulgarisationProduit vulgarisationProduit);    
}
