// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.service;

import com.polypharm.gescom.domain.VulgarisationProduit;
import com.polypharm.gescom.repository.VulgarisationProduitRepository;
import com.polypharm.gescom.service.VulgarisationProduitServiceImpl;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect VulgarisationProduitServiceImpl_Roo_Service {
    
    declare @type: VulgarisationProduitServiceImpl: @Service;
    
    declare @type: VulgarisationProduitServiceImpl: @Transactional;
    
    @Autowired
    VulgarisationProduitRepository VulgarisationProduitServiceImpl.vulgarisationProduitRepository;
    
    public long VulgarisationProduitServiceImpl.countAllVulgarisationProduits() {
        return vulgarisationProduitRepository.count();
    }
    
    public void VulgarisationProduitServiceImpl.deleteVulgarisationProduit(VulgarisationProduit vulgarisationProduit) {
        vulgarisationProduitRepository.delete(vulgarisationProduit);
    }
    
    public VulgarisationProduit VulgarisationProduitServiceImpl.findVulgarisationProduit(Long id) {
        return vulgarisationProduitRepository.findOne(id);
    }
    
    public List<VulgarisationProduit> VulgarisationProduitServiceImpl.findAllVulgarisationProduits() {
        return vulgarisationProduitRepository.findAll();
    }
    
    public List<VulgarisationProduit> VulgarisationProduitServiceImpl.findVulgarisationProduitEntries(int firstResult, int maxResults) {
        return vulgarisationProduitRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
    }
    
    public void VulgarisationProduitServiceImpl.saveVulgarisationProduit(VulgarisationProduit vulgarisationProduit) {
        vulgarisationProduitRepository.save(vulgarisationProduit);
    }
    
    public VulgarisationProduit VulgarisationProduitServiceImpl.updateVulgarisationProduit(VulgarisationProduit vulgarisationProduit) {
        return vulgarisationProduitRepository.save(vulgarisationProduit);
    }
    
}
