// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.repository;

import com.polypharm.gescom.domain.ConseilClient;
import com.polypharm.gescom.repository.ConseilClientRepository;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

privileged aspect ConseilClientRepository_Roo_Jpa_Repository {
    
    declare parents: ConseilClientRepository extends JpaRepository<ConseilClient, Long>;
    
    declare parents: ConseilClientRepository extends JpaSpecificationExecutor<ConseilClient>;
    
    declare @type: ConseilClientRepository: @Repository;
    
}
