// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.repository;

import com.polypharm.gescom.domain.FamilleProduit;
import com.polypharm.gescom.repository.FamilleProduitRepository;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

privileged aspect FamilleProduitRepository_Roo_Jpa_Repository {
    
    declare parents: FamilleProduitRepository extends JpaRepository<FamilleProduit, Long>;
    
    declare parents: FamilleProduitRepository extends JpaSpecificationExecutor<FamilleProduit>;
    
    declare @type: FamilleProduitRepository: @Repository;
    
}
