// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.repository;

import com.polypharm.gescom.domain.FormationUtilisateur;
import com.polypharm.gescom.repository.FormationUtilisateurRepository;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

privileged aspect FormationUtilisateurRepository_Roo_Jpa_Repository {
    
    declare parents: FormationUtilisateurRepository extends JpaRepository<FormationUtilisateur, Long>;
    
    declare parents: FormationUtilisateurRepository extends JpaSpecificationExecutor<FormationUtilisateur>;
    
    declare @type: FormationUtilisateurRepository: @Repository;
    
}
