// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.repository;

import com.polypharm.gescom.domain.Installation;
import com.polypharm.gescom.repository.InstallationRepository;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

privileged aspect InstallationRepository_Roo_Jpa_Repository {
    
    declare parents: InstallationRepository extends JpaRepository<Installation, Long>;
    
    declare parents: InstallationRepository extends JpaSpecificationExecutor<Installation>;
    
    declare @type: InstallationRepository: @Repository;
    
}
