// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.repository;

import com.polypharm.gescom.domain.Livraison;
import com.polypharm.gescom.repository.LivraisonRepository;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

privileged aspect LivraisonRepository_Roo_Jpa_Repository {
    
    declare parents: LivraisonRepository extends JpaRepository<Livraison, Long>;
    
    declare parents: LivraisonRepository extends JpaSpecificationExecutor<Livraison>;
    
    declare @type: LivraisonRepository: @Repository;
    
}
