// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.repository;

import com.polypharm.gescom.domain.Personnel;
import com.polypharm.gescom.repository.PersonnelRepository;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

privileged aspect PersonnelRepository_Roo_Jpa_Repository {
    
    declare parents: PersonnelRepository extends JpaRepository<Personnel, Long>;
    
    declare parents: PersonnelRepository extends JpaSpecificationExecutor<Personnel>;
    
    declare @type: PersonnelRepository: @Repository;
    
}
