// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.repository;

import com.polypharm.gescom.domain.Produit;
import com.polypharm.gescom.repository.ProduitRepository;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

privileged aspect ProduitRepository_Roo_Jpa_Repository {
    
    declare parents: ProduitRepository extends JpaRepository<Produit, Long>;
    
    declare parents: ProduitRepository extends JpaSpecificationExecutor<Produit>;
    
    declare @type: ProduitRepository: @Repository;
    
}
