// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.repository;

import com.polypharm.gescom.domain.RecrutementProspect;
import com.polypharm.gescom.repository.RecrutementProspectRepository;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

privileged aspect RecrutementProspectRepository_Roo_Jpa_Repository {
    
    declare parents: RecrutementProspectRepository extends JpaRepository<RecrutementProspect, Long>;
    
    declare parents: RecrutementProspectRepository extends JpaSpecificationExecutor<RecrutementProspect>;
    
    declare @type: RecrutementProspectRepository: @Repository;
    
}
