// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.repository;

import com.polypharm.gescom.domain.SuiviStock;
import com.polypharm.gescom.repository.SuiviStockProspectRepository;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

privileged aspect SuiviStockProspectRepository_Roo_Jpa_Repository {
    
    declare parents: SuiviStockProspectRepository extends JpaRepository<SuiviStock, Long>;
    
    declare parents: SuiviStockProspectRepository extends JpaSpecificationExecutor<SuiviStock>;
    
    declare @type: SuiviStockProspectRepository: @Repository;
    
}
