// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.repository;

import com.polypharm.gescom.domain.VeilleConcurrentielleProduit;
import com.polypharm.gescom.repository.VeilleConcurentielleProduitRepository;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

privileged aspect VeilleConcurentielleProduitRepository_Roo_Jpa_Repository {
    
    declare parents: VeilleConcurentielleProduitRepository extends JpaRepository<VeilleConcurrentielleProduit, Long>;
    
    declare parents: VeilleConcurentielleProduitRepository extends JpaSpecificationExecutor<VeilleConcurrentielleProduit>;
    
    declare @type: VeilleConcurentielleProduitRepository: @Repository;
    
}
