// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.repository;

import com.polypharm.gescom.domain.VulgarisationProduit;
import com.polypharm.gescom.repository.VulgarisationProduitRepository;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

privileged aspect VulgarisationProduitRepository_Roo_Jpa_Repository {
    
    declare parents: VulgarisationProduitRepository extends JpaRepository<VulgarisationProduit, Long>;
    
    declare parents: VulgarisationProduitRepository extends JpaSpecificationExecutor<VulgarisationProduit>;
    
    declare @type: VulgarisationProduitRepository: @Repository;
    
}
