// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.domain;

import com.polypharm.gescom.domain.Agence;

privileged aspect Agence_Roo_JavaBean {
    
    public String Agence.getNom() {
        return this.nom;
    }
    
    public void Agence.setNom(String nom) {
        this.nom = nom;
    }
    
    public String Agence.getDescription() {
        return this.description;
    }
    
    public void Agence.setDescription(String description) {
        this.description = description;
    }
    
}
