// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.domain;

import com.polypharm.gescom.domain.Agence;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Agence_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager Agence.entityManager;
    
    public static final EntityManager Agence.entityManager() {
        EntityManager em = new Agence().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Agence.countAgences() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Agence o", Long.class).getSingleResult();
    }
    
    public static List<Agence> Agence.findAllAgences() {
        return entityManager().createQuery("SELECT o FROM Agence o", Agence.class).getResultList();
    }
    
    public static Agence Agence.findAgence(Long id) {
        if (id == null) return null;
        return entityManager().find(Agence.class, id);
    }
    
    public static List<Agence> Agence.findAgenceEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Agence o", Agence.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void Agence.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void Agence.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Agence attached = Agence.findAgence(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void Agence.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void Agence.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public Agence Agence.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Agence merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
