// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.domain;

import com.polypharm.gescom.domain.Agence;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect Agence_Roo_Jpa_Entity {
    
    declare @type: Agence: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long Agence.id;
    
    @Version
    @Column(name = "version")
    private Integer Agence.version;
    
    public Long Agence.getId() {
        return this.id;
    }
    
    public void Agence.setId(Long id) {
        this.id = id;
    }
    
    public Integer Agence.getVersion() {
        return this.version;
    }
    
    public void Agence.setVersion(Integer version) {
        this.version = version;
    }
    
}
