// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.domain;

import com.polypharm.gescom.domain.AssistanceCommerciale;

privileged aspect AssistanceCommerciale_Roo_JavaBean {
    
    public String AssistanceCommerciale.getObjetAssistance() {
        return this.objetAssistance;
    }
    
    public void AssistanceCommerciale.setObjetAssistance(String objetAssistance) {
        this.objetAssistance = objetAssistance;
    }
    
    public String AssistanceCommerciale.getCollegueAssiste() {
        return this.collegueAssiste;
    }
    
    public void AssistanceCommerciale.setCollegueAssiste(String collegueAssiste) {
        this.collegueAssiste = collegueAssiste;
    }
    
}
