// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.domain;

import com.polypharm.gescom.domain.AssistanceCommerciale;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AssistanceCommerciale_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager AssistanceCommerciale.entityManager;
    
    public static final EntityManager AssistanceCommerciale.entityManager() {
        EntityManager em = new AssistanceCommerciale().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long AssistanceCommerciale.countAssistanceCommerciales() {
        return entityManager().createQuery("SELECT COUNT(o) FROM AssistanceCommerciale o", Long.class).getSingleResult();
    }
    
    public static List<AssistanceCommerciale> AssistanceCommerciale.findAllAssistanceCommerciales() {
        return entityManager().createQuery("SELECT o FROM AssistanceCommerciale o", AssistanceCommerciale.class).getResultList();
    }
    
    public static AssistanceCommerciale AssistanceCommerciale.findAssistanceCommerciale(Long id) {
        if (id == null) return null;
        return entityManager().find(AssistanceCommerciale.class, id);
    }
    
    public static List<AssistanceCommerciale> AssistanceCommerciale.findAssistanceCommercialeEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM AssistanceCommerciale o", AssistanceCommerciale.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void AssistanceCommerciale.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void AssistanceCommerciale.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            AssistanceCommerciale attached = AssistanceCommerciale.findAssistanceCommerciale(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void AssistanceCommerciale.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void AssistanceCommerciale.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public AssistanceCommerciale AssistanceCommerciale.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        AssistanceCommerciale merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
