// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.domain;

import com.polypharm.gescom.domain.AutoFormationEntreprise;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect AutoFormationEntreprise_Roo_Jpa_Entity {
    
    declare @type: AutoFormationEntreprise: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long AutoFormationEntreprise.id;
    
    @Version
    @Column(name = "version")
    private Integer AutoFormationEntreprise.version;
    
    public Long AutoFormationEntreprise.getId() {
        return this.id;
    }
    
    public void AutoFormationEntreprise.setId(Long id) {
        this.id = id;
    }
    
    public Integer AutoFormationEntreprise.getVersion() {
        return this.version;
    }
    
    public void AutoFormationEntreprise.setVersion(Integer version) {
        this.version = version;
    }
    
}
