// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.domain;

import com.polypharm.gescom.domain.AutoFormationEntreprise;
import java.util.Date;

privileged aspect AutoFormationEntreprise_Roo_JavaBean {
    
    public String AutoFormationEntreprise.getObjetAutoFormation() {
        return this.objetAutoFormation;
    }
    
    public void AutoFormationEntreprise.setObjetAutoFormation(String objetAutoFormation) {
        this.objetAutoFormation = objetAutoFormation;
    }
    
    public Integer AutoFormationEntreprise.getNbreInterlocuteur() {
        return this.nbreInterlocuteur;
    }
    
    public void AutoFormationEntreprise.setNbreInterlocuteur(Integer nbreInterlocuteur) {
        this.nbreInterlocuteur = nbreInterlocuteur;
    }
    
    public String AutoFormationEntreprise.getDuree() {
        return this.duree;
    }
    
    public void AutoFormationEntreprise.setDuree(String duree) {
        this.duree = duree;
    }
    
    public Date AutoFormationEntreprise.getDateAutoFormation() {
        return this.dateAutoFormation;
    }
    
    public void AutoFormationEntreprise.setDateAutoFormation(Date dateAutoFormation) {
        this.dateAutoFormation = dateAutoFormation;
    }
    
}
