// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.domain;

import com.polypharm.gescom.domain.Client;
import java.util.Date;

privileged aspect Client_Roo_JavaBean {
    
    public String Client.getNom() {
        return this.nom;
    }
    
    public void Client.setNom(String nom) {
        this.nom = nom;
    }
    
    public String Client.getTelephone() {
        return this.telephone;
    }
    
    public void Client.setTelephone(String telephone) {
        this.telephone = telephone;
    }
    
    public String Client.getNumeroCarteContribuable() {
        return this.numeroCarteContribuable;
    }
    
    public void Client.setNumeroCarteContribuable(String numeroCarteContribuable) {
        this.numeroCarteContribuable = numeroCarteContribuable;
    }
    
    public Date Client.getExpirationCarteContribuable() {
        return this.expirationCarteContribuable;
    }
    
    public void Client.setExpirationCarteContribuable(Date expirationCarteContribuable) {
        this.expirationCarteContribuable = expirationCarteContribuable;
    }
    
    public String Client.getRegimeFiscal() {
        return this.regimeFiscal;
    }
    
    public void Client.setRegimeFiscal(String regimeFiscal) {
        this.regimeFiscal = regimeFiscal;
    }
    
    public Date Client.getExpirationPatente() {
        return this.expirationPatente;
    }
    
    public void Client.setExpirationPatente(Date expirationPatente) {
        this.expirationPatente = expirationPatente;
    }
    
    public String Client.getLocalisation() {
        return this.localisation;
    }
    
    public void Client.setLocalisation(String localisation) {
        this.localisation = localisation;
    }
    
    public Boolean Client.getColleterTva() {
        return this.colleterTva;
    }
    
    public void Client.setColleterTva(Boolean colleterTva) {
        this.colleterTva = colleterTva;
    }
    
    public String Client.getNumAttestationNonRedevance() {
        return this.numAttestationNonRedevance;
    }
    
    public void Client.setNumAttestationNonRedevance(String numAttestationNonRedevance) {
        this.numAttestationNonRedevance = numAttestationNonRedevance;
    }
    
    public String Client.getNumAttestationSoumissionCNPS() {
        return this.numAttestationSoumissionCNPS;
    }
    
    public void Client.setNumAttestationSoumissionCNPS(String numAttestationSoumissionCNPS) {
        this.numAttestationSoumissionCNPS = numAttestationSoumissionCNPS;
    }
    
}
