// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.domain;

import com.polypharm.gescom.domain.Client;
import com.polypharm.gescom.domain.ConseilClient;

privileged aspect ConseilClient_Roo_JavaBean {
    
    public String ConseilClient.getObjetDuConseil() {
        return this.objetDuConseil;
    }
    
    public void ConseilClient.setObjetDuConseil(String objetDuConseil) {
        this.objetDuConseil = objetDuConseil;
    }
    
    public Client ConseilClient.getClient() {
        return this.client;
    }
    
    public void ConseilClient.setClient(Client client) {
        this.client = client;
    }
    
    public String ConseilClient.getInterlocuteur() {
        return this.interlocuteur;
    }
    
    public void ConseilClient.setInterlocuteur(String interlocuteur) {
        this.interlocuteur = interlocuteur;
    }
    
}
