// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.domain;

import com.polypharm.gescom.domain.DossierCreance;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect DossierCreance_Roo_Configurable {
    
    declare @type: DossierCreance: @Configurable;
    
}
