// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.domain;

import com.polypharm.gescom.domain.Client;
import com.polypharm.gescom.domain.DossierCreance;
import com.polypharm.gescom.domain.Personnel;
import java.util.Date;

privileged aspect DossierCreance_Roo_JavaBean {
    
    public String DossierCreance.getNumBonCommande() {
        return this.numBonCommande;
    }
    
    public void DossierCreance.setNumBonCommande(String numBonCommande) {
        this.numBonCommande = numBonCommande;
    }
    
    public String DossierCreance.getNumBonLivraison() {
        return this.numBonLivraison;
    }
    
    public void DossierCreance.setNumBonLivraison(String numBonLivraison) {
        this.numBonLivraison = numBonLivraison;
    }
    
    public String DossierCreance.getNumFacture() {
        return this.numFacture;
    }
    
    public void DossierCreance.setNumFacture(String numFacture) {
        this.numFacture = numFacture;
    }
    
    public String DossierCreance.getNatureGarantie() {
        return this.natureGarantie;
    }
    
    public void DossierCreance.setNatureGarantie(String natureGarantie) {
        this.natureGarantie = natureGarantie;
    }
    
    public String DossierCreance.getNumContratCreance() {
        return this.numContratCreance;
    }
    
    public void DossierCreance.setNumContratCreance(String numContratCreance) {
        this.numContratCreance = numContratCreance;
    }
    
    public Date DossierCreance.getDateEmission() {
        return this.dateEmission;
    }
    
    public void DossierCreance.setDateEmission(Date dateEmission) {
        this.dateEmission = dateEmission;
    }
    
    public Date DossierCreance.getDateEchance() {
        return this.dateEchance;
    }
    
    public void DossierCreance.setDateEchance(Date dateEchance) {
        this.dateEchance = dateEchance;
    }
    
    public Client DossierCreance.getClient() {
        return this.client;
    }
    
    public void DossierCreance.setClient(Client client) {
        this.client = client;
    }
    
    public Personnel DossierCreance.getAuteur() {
        return this.auteur;
    }
    
    public void DossierCreance.setAuteur(Personnel auteur) {
        this.auteur = auteur;
    }
    
}
