// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.domain;

import com.polypharm.gescom.domain.DossierCreance;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DossierCreance_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager DossierCreance.entityManager;
    
    public static final EntityManager DossierCreance.entityManager() {
        EntityManager em = new DossierCreance().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long DossierCreance.countDossierCreances() {
        return entityManager().createQuery("SELECT COUNT(o) FROM DossierCreance o", Long.class).getSingleResult();
    }
    
    public static List<DossierCreance> DossierCreance.findAllDossierCreances() {
        return entityManager().createQuery("SELECT o FROM DossierCreance o", DossierCreance.class).getResultList();
    }
    
    public static DossierCreance DossierCreance.findDossierCreance(Long id) {
        if (id == null) return null;
        return entityManager().find(DossierCreance.class, id);
    }
    
    public static List<DossierCreance> DossierCreance.findDossierCreanceEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM DossierCreance o", DossierCreance.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void DossierCreance.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void DossierCreance.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            DossierCreance attached = DossierCreance.findDossierCreance(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void DossierCreance.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void DossierCreance.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public DossierCreance DossierCreance.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        DossierCreance merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
