// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.domain;

import com.polypharm.gescom.domain.FamilleProduit;

privileged aspect FamilleProduit_Roo_JavaBean {
    
    public String FamilleProduit.getNom() {
        return this.nom;
    }
    
    public void FamilleProduit.setNom(String nom) {
        this.nom = nom;
    }
    
    public String FamilleProduit.getDescription() {
        return this.description;
    }
    
    public void FamilleProduit.setDescription(String description) {
        this.description = description;
    }
    
}
