// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.domain;

import com.polypharm.gescom.domain.FamilleProduit;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect FamilleProduit_Roo_Jpa_Entity {
    
    declare @type: FamilleProduit: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long FamilleProduit.id;
    
    @Version
    @Column(name = "version")
    private Integer FamilleProduit.version;
    
    public Long FamilleProduit.getId() {
        return this.id;
    }
    
    public void FamilleProduit.setId(Long id) {
        this.id = id;
    }
    
    public Integer FamilleProduit.getVersion() {
        return this.version;
    }
    
    public void FamilleProduit.setVersion(Integer version) {
        this.version = version;
    }
    
}
