// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.domain;

import com.polypharm.gescom.domain.FamilleProduit;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FamilleProduit_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager FamilleProduit.entityManager;
    
    public static final List<String> FamilleProduit.fieldNames4OrderClauseFilter = java.util.Arrays.asList("nom", "description");
    
    public static final EntityManager FamilleProduit.entityManager() {
        EntityManager em = new FamilleProduit().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long FamilleProduit.countFamilleProduits() {
        return entityManager().createQuery("SELECT COUNT(o) FROM FamilleProduit o", Long.class).getSingleResult();
    }
    
    public static List<FamilleProduit> FamilleProduit.findAllFamilleProduits() {
        return entityManager().createQuery("SELECT o FROM FamilleProduit o", FamilleProduit.class).getResultList();
    }
    
    public static List<FamilleProduit> FamilleProduit.findAllFamilleProduits(String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM FamilleProduit o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, FamilleProduit.class).getResultList();
    }
    
    public static FamilleProduit FamilleProduit.findFamilleProduit(Long id) {
        if (id == null) return null;
        return entityManager().find(FamilleProduit.class, id);
    }
    
    public static List<FamilleProduit> FamilleProduit.findFamilleProduitEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM FamilleProduit o", FamilleProduit.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    public static List<FamilleProduit> FamilleProduit.findFamilleProduitEntries(int firstResult, int maxResults, String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM FamilleProduit o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, FamilleProduit.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void FamilleProduit.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void FamilleProduit.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            FamilleProduit attached = FamilleProduit.findFamilleProduit(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void FamilleProduit.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void FamilleProduit.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public FamilleProduit FamilleProduit.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        FamilleProduit merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
