// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.domain;

import com.polypharm.gescom.domain.FormationUtilisateur;
import java.util.Date;

privileged aspect FormationUtilisateur_Roo_JavaBean {
    
    public String FormationUtilisateur.getObjetFormation() {
        return this.objetFormation;
    }
    
    public void FormationUtilisateur.setObjetFormation(String objetFormation) {
        this.objetFormation = objetFormation;
    }
    
    public Integer FormationUtilisateur.getNbreInterlocuteur() {
        return this.nbreInterlocuteur;
    }
    
    public void FormationUtilisateur.setNbreInterlocuteur(Integer nbreInterlocuteur) {
        this.nbreInterlocuteur = nbreInterlocuteur;
    }
    
    public String FormationUtilisateur.getDureFormation() {
        return this.dureFormation;
    }
    
    public void FormationUtilisateur.setDureFormation(String dureFormation) {
        this.dureFormation = dureFormation;
    }
    
    public Date FormationUtilisateur.getDateFormation() {
        return this.dateFormation;
    }
    
    public void FormationUtilisateur.setDateFormation(Date dateFormation) {
        this.dateFormation = dateFormation;
    }
    
}
