// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.domain;

import com.polypharm.gescom.domain.FormationUtilisateur;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FormationUtilisateur_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager FormationUtilisateur.entityManager;
    
    public static final EntityManager FormationUtilisateur.entityManager() {
        EntityManager em = new FormationUtilisateur().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long FormationUtilisateur.countFormationUtilisateurs() {
        return entityManager().createQuery("SELECT COUNT(o) FROM FormationUtilisateur o", Long.class).getSingleResult();
    }
    
    public static List<FormationUtilisateur> FormationUtilisateur.findAllFormationUtilisateurs() {
        return entityManager().createQuery("SELECT o FROM FormationUtilisateur o", FormationUtilisateur.class).getResultList();
    }
    
    public static FormationUtilisateur FormationUtilisateur.findFormationUtilisateur(Long id) {
        if (id == null) return null;
        return entityManager().find(FormationUtilisateur.class, id);
    }
    
    public static List<FormationUtilisateur> FormationUtilisateur.findFormationUtilisateurEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM FormationUtilisateur o", FormationUtilisateur.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void FormationUtilisateur.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void FormationUtilisateur.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            FormationUtilisateur attached = FormationUtilisateur.findFormationUtilisateur(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void FormationUtilisateur.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void FormationUtilisateur.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public FormationUtilisateur FormationUtilisateur.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        FormationUtilisateur merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
