// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.domain;

import com.polypharm.gescom.domain.Installation;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Installation_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager Installation.entityManager;
    
    public static final List<String> Installation.fieldNames4OrderClauseFilter = java.util.Arrays.asList("nomEquipement", "client", "dateInstallation", "auteur");
    
    public static final EntityManager Installation.entityManager() {
        EntityManager em = new Installation().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Installation.countInstallations() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Installation o", Long.class).getSingleResult();
    }
    
    public static List<Installation> Installation.findAllInstallations() {
        return entityManager().createQuery("SELECT o FROM Installation o", Installation.class).getResultList();
    }
    
    public static List<Installation> Installation.findAllInstallations(String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM Installation o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, Installation.class).getResultList();
    }
    
    public static Installation Installation.findInstallation(Long id) {
        if (id == null) return null;
        return entityManager().find(Installation.class, id);
    }
    
    public static List<Installation> Installation.findInstallationEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Installation o", Installation.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    public static List<Installation> Installation.findInstallationEntries(int firstResult, int maxResults, String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM Installation o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, Installation.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void Installation.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void Installation.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Installation attached = Installation.findInstallation(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void Installation.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void Installation.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public Installation Installation.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Installation merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
