// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.domain;

import com.polypharm.gescom.domain.Installation;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect Installation_Roo_Jpa_Entity {
    
    declare @type: Installation: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long Installation.id;
    
    @Version
    @Column(name = "version")
    private Integer Installation.version;
    
    public Long Installation.getId() {
        return this.id;
    }
    
    public void Installation.setId(Long id) {
        this.id = id;
    }
    
    public Integer Installation.getVersion() {
        return this.version;
    }
    
    public void Installation.setVersion(Integer version) {
        this.version = version;
    }
    
}
