// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.domain;

import com.polypharm.gescom.domain.Client;
import com.polypharm.gescom.domain.Installation;
import com.polypharm.gescom.domain.Personnel;
import java.util.Date;

privileged aspect Installation_Roo_JavaBean {
    
    public String Installation.getNomEquipement() {
        return this.nomEquipement;
    }
    
    public void Installation.setNomEquipement(String nomEquipement) {
        this.nomEquipement = nomEquipement;
    }
    
    public Client Installation.getClient() {
        return this.client;
    }
    
    public void Installation.setClient(Client client) {
        this.client = client;
    }
    
    public Date Installation.getDateInstallation() {
        return this.dateInstallation;
    }
    
    public void Installation.setDateInstallation(Date dateInstallation) {
        this.dateInstallation = dateInstallation;
    }
    
    public Personnel Installation.getAuteur() {
        return this.auteur;
    }
    
    public void Installation.setAuteur(Personnel auteur) {
        this.auteur = auteur;
    }
    
}
