// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.domain;

import com.polypharm.gescom.domain.Client;
import com.polypharm.gescom.domain.Livraison;

privileged aspect Livraison_Roo_JavaBean {
    
    public String Livraison.getNumeroBodereauLivraison() {
        return this.numeroBodereauLivraison;
    }
    
    public void Livraison.setNumeroBodereauLivraison(String numeroBodereauLivraison) {
        this.numeroBodereauLivraison = numeroBodereauLivraison;
    }
    
    public Client Livraison.getClient() {
        return this.client;
    }
    
    public void Livraison.setClient(Client client) {
        this.client = client;
    }
    
    public String Livraison.getDureLivraison() {
        return this.dureLivraison;
    }
    
    public void Livraison.setDureLivraison(String dureLivraison) {
        this.dureLivraison = dureLivraison;
    }
    
}
