// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.domain;

import com.polypharm.gescom.domain.Livraison;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect Livraison_Roo_Jpa_Entity {
    
    declare @type: Livraison: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long Livraison.id;
    
    @Version
    @Column(name = "version")
    private Integer Livraison.version;
    
    public Long Livraison.getId() {
        return this.id;
    }
    
    public void Livraison.setId(Long id) {
        this.id = id;
    }
    
    public Integer Livraison.getVersion() {
        return this.version;
    }
    
    public void Livraison.setVersion(Integer version) {
        this.version = version;
    }
    
}
