// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.domain;

import com.polypharm.gescom.domain.Montage;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect Montage_Roo_Jpa_Entity {
    
    declare @type: Montage: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long Montage.id;
    
    @Version
    @Column(name = "version")
    private Integer Montage.version;
    
    public Long Montage.getId() {
        return this.id;
    }
    
    public void Montage.setId(Long id) {
        this.id = id;
    }
    
    public Integer Montage.getVersion() {
        return this.version;
    }
    
    public void Montage.setVersion(Integer version) {
        this.version = version;
    }
    
}
