// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.domain;

import com.polypharm.gescom.domain.Montage;
import java.util.Date;

privileged aspect Montage_Roo_JavaBean {
    
    public String Montage.getNomEquipement() {
        return this.nomEquipement;
    }
    
    public void Montage.setNomEquipement(String nomEquipement) {
        this.nomEquipement = nomEquipement;
    }
    
    public String Montage.getDuree() {
        return this.duree;
    }
    
    public void Montage.setDuree(String duree) {
        this.duree = duree;
    }
    
    public Date Montage.getDateMontage() {
        return this.dateMontage;
    }
    
    public void Montage.setDateMontage(Date dateMontage) {
        this.dateMontage = dateMontage;
    }
    
}
