// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.domain;

import com.polypharm.gescom.domain.Personnel;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Personnel_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager Personnel.entityManager;
    
    public static final EntityManager Personnel.entityManager() {
        EntityManager em = new Personnel().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Personnel.countPersonnels() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Personnel o", Long.class).getSingleResult();
    }
    
    public static List<Personnel> Personnel.findAllPersonnels() {
        return entityManager().createQuery("SELECT o FROM Personnel o", Personnel.class).getResultList();
    }
    
    public static Personnel Personnel.findPersonnel(Long id) {
        if (id == null) return null;
        return entityManager().find(Personnel.class, id);
    }
    
    public static List<Personnel> Personnel.findPersonnelEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Personnel o", Personnel.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void Personnel.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void Personnel.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Personnel attached = Personnel.findPersonnel(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void Personnel.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void Personnel.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public Personnel Personnel.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Personnel merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
