// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.domain;

import com.polypharm.gescom.domain.Personnel;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect Personnel_Roo_Jpa_Entity {
    
    declare @type: Personnel: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long Personnel.id;
    
    @Version
    @Column(name = "version")
    private Integer Personnel.version;
    
    public Long Personnel.getId() {
        return this.id;
    }
    
    public void Personnel.setId(Long id) {
        this.id = id;
    }
    
    public Integer Personnel.getVersion() {
        return this.version;
    }
    
    public void Personnel.setVersion(Integer version) {
        this.version = version;
    }
    
}
