// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.domain;

import com.polypharm.gescom.domain.FamilleProduit;
import com.polypharm.gescom.domain.Produit;

privileged aspect Produit_Roo_JavaBean {
    
    public String Produit.getNom() {
        return this.nom;
    }
    
    public void Produit.setNom(String nom) {
        this.nom = nom;
    }
    
    public String Produit.getDescription() {
        return this.description;
    }
    
    public void Produit.setDescription(String description) {
        this.description = description;
    }
    
    public FamilleProduit Produit.getFamilleProduit() {
        return this.familleProduit;
    }
    
    public void Produit.setFamilleProduit(FamilleProduit familleProduit) {
        this.familleProduit = familleProduit;
    }
    
    public String Produit.getMarque() {
        return this.marque;
    }
    
    public void Produit.setMarque(String marque) {
        this.marque = marque;
    }
    
}
