// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.domain;

import com.polypharm.gescom.domain.Produit;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect Produit_Roo_Jpa_Entity {
    
    declare @type: Produit: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long Produit.id;
    
    @Version
    @Column(name = "version")
    private Integer Produit.version;
    
    public Long Produit.getId() {
        return this.id;
    }
    
    public void Produit.setId(Long id) {
        this.id = id;
    }
    
    public Integer Produit.getVersion() {
        return this.version;
    }
    
    public void Produit.setVersion(Integer version) {
        this.version = version;
    }
    
}
