// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.domain;

import com.polypharm.gescom.domain.ProjetCommande;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect ProjetCommande_Roo_Jpa_Entity {
    
    declare @type: ProjetCommande: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long ProjetCommande.id;
    
    @Version
    @Column(name = "version")
    private Integer ProjetCommande.version;
    
    public Long ProjetCommande.getId() {
        return this.id;
    }
    
    public void ProjetCommande.setId(Long id) {
        this.id = id;
    }
    
    public Integer ProjetCommande.getVersion() {
        return this.version;
    }
    
    public void ProjetCommande.setVersion(Integer version) {
        this.version = version;
    }
    
}
