// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.domain;

import com.polypharm.gescom.domain.Client;
import com.polypharm.gescom.domain.ProjetCommande;

privileged aspect ProjetCommande_Roo_JavaBean {
    
    public String ProjetCommande.getObjetProjet() {
        return this.objetProjet;
    }
    
    public void ProjetCommande.setObjetProjet(String objetProjet) {
        this.objetProjet = objetProjet;
    }
    
    public String ProjetCommande.getReferencePROFORMA() {
        return this.referencePROFORMA;
    }
    
    public void ProjetCommande.setReferencePROFORMA(String referencePROFORMA) {
        this.referencePROFORMA = referencePROFORMA;
    }
    
    public String ProjetCommande.getReferenceBonCommande() {
        return this.referenceBonCommande;
    }
    
    public void ProjetCommande.setReferenceBonCommande(String referenceBonCommande) {
        this.referenceBonCommande = referenceBonCommande;
    }
    
    public Client ProjetCommande.getClientConcerne() {
        return this.clientConcerne;
    }
    
    public void ProjetCommande.setClientConcerne(Client clientConcerne) {
        this.clientConcerne = clientConcerne;
    }
    
    public String ProjetCommande.getInterlocuteurPrincipal() {
        return this.interlocuteurPrincipal;
    }
    
    public void ProjetCommande.setInterlocuteurPrincipal(String interlocuteurPrincipal) {
        this.interlocuteurPrincipal = interlocuteurPrincipal;
    }
    
}
