// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.domain;

import com.polypharm.gescom.domain.RecrutementProspect;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect RecrutementProspect_Roo_Jpa_Entity {
    
    declare @type: RecrutementProspect: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long RecrutementProspect.id;
    
    @Version
    @Column(name = "version")
    private Integer RecrutementProspect.version;
    
    public Long RecrutementProspect.getId() {
        return this.id;
    }
    
    public void RecrutementProspect.setId(Long id) {
        this.id = id;
    }
    
    public Integer RecrutementProspect.getVersion() {
        return this.version;
    }
    
    public void RecrutementProspect.setVersion(Integer version) {
        this.version = version;
    }
    
}
