// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.domain;

import com.polypharm.gescom.domain.Personnel;
import com.polypharm.gescom.domain.RecrutementProspect;
import java.util.Date;

privileged aspect RecrutementProspect_Roo_JavaBean {
    
    public String RecrutementProspect.getDenominationProspect() {
        return this.denominationProspect;
    }
    
    public void RecrutementProspect.setDenominationProspect(String denominationProspect) {
        this.denominationProspect = denominationProspect;
    }
    
    public String RecrutementProspect.getFctionInterlocuteur() {
        return this.fctionInterlocuteur;
    }
    
    public void RecrutementProspect.setFctionInterlocuteur(String fctionInterlocuteur) {
        this.fctionInterlocuteur = fctionInterlocuteur;
    }
    
    public String RecrutementProspect.getTelephone() {
        return this.telephone;
    }
    
    public void RecrutementProspect.setTelephone(String telephone) {
        this.telephone = telephone;
    }
    
    public String RecrutementProspect.getEmail() {
        return this.email;
    }
    
    public void RecrutementProspect.setEmail(String email) {
        this.email = email;
    }
    
    public String RecrutementProspect.getBoitePostale() {
        return this.boitePostale;
    }
    
    public void RecrutementProspect.setBoitePostale(String boitePostale) {
        this.boitePostale = boitePostale;
    }
    
    public String RecrutementProspect.getLocalisation() {
        return this.localisation;
    }
    
    public void RecrutementProspect.setLocalisation(String localisation) {
        this.localisation = localisation;
    }
    
    public Date RecrutementProspect.getDateRecrutement() {
        return this.dateRecrutement;
    }
    
    public void RecrutementProspect.setDateRecrutement(Date dateRecrutement) {
        this.dateRecrutement = dateRecrutement;
    }
    
    public Personnel RecrutementProspect.getAuteur() {
        return this.auteur;
    }
    
    public void RecrutementProspect.setAuteur(Personnel auteur) {
        this.auteur = auteur;
    }
    
}
