package com.polypharm.gescom.domain;

public enum RoleName {

    RESPONSABLE_COMMERCIALE, RESPONSABLE_FORCE_DE_VENTE, RESPONSABLE_COMPTABLE, RESPONSABLE_AUDIT, RESPONSABLE_CONTROLE, RESPONSABLE_INFORMATIQUE
}
