// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.domain;

import com.polypharm.gescom.domain.SuiviStock;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect SuiviStock_Roo_Jpa_Entity {
    
    declare @type: SuiviStock: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long SuiviStock.id;
    
    @Version
    @Column(name = "version")
    private Integer SuiviStock.version;
    
    public Long SuiviStock.getId() {
        return this.id;
    }
    
    public void SuiviStock.setId(Long id) {
        this.id = id;
    }
    
    public Integer SuiviStock.getVersion() {
        return this.version;
    }
    
    public void SuiviStock.setVersion(Integer version) {
        this.version = version;
    }
    
}
