// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.domain;

import com.polypharm.gescom.domain.SuiviStock;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SuiviStock_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager SuiviStock.entityManager;
    
    public static final EntityManager SuiviStock.entityManager() {
        EntityManager em = new SuiviStock().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long SuiviStock.countSuiviStocks() {
        return entityManager().createQuery("SELECT COUNT(o) FROM SuiviStock o", Long.class).getSingleResult();
    }
    
    public static List<SuiviStock> SuiviStock.findAllSuiviStocks() {
        return entityManager().createQuery("SELECT o FROM SuiviStock o", SuiviStock.class).getResultList();
    }
    
    public static SuiviStock SuiviStock.findSuiviStock(Long id) {
        if (id == null) return null;
        return entityManager().find(SuiviStock.class, id);
    }
    
    public static List<SuiviStock> SuiviStock.findSuiviStockEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM SuiviStock o", SuiviStock.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void SuiviStock.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void SuiviStock.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            SuiviStock attached = SuiviStock.findSuiviStock(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void SuiviStock.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void SuiviStock.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public SuiviStock SuiviStock.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        SuiviStock merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
