// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.domain;

import com.polypharm.gescom.domain.Produit;
import com.polypharm.gescom.domain.SuiviStock;
import java.util.Date;

privileged aspect SuiviStock_Roo_JavaBean {
    
    public Produit SuiviStock.getProduit() {
        return this.produit;
    }
    
    public void SuiviStock.setProduit(Produit produit) {
        this.produit = produit;
    }
    
    public Integer SuiviStock.getDerniereQteCommande() {
        return this.derniereQteCommande;
    }
    
    public void SuiviStock.setDerniereQteCommande(Integer derniereQteCommande) {
        this.derniereQteCommande = derniereQteCommande;
    }
    
    public Integer SuiviStock.getQteStock() {
        return this.qteStock;
    }
    
    public void SuiviStock.setQteStock(Integer qteStock) {
        this.qteStock = qteStock;
    }
    
    public Date SuiviStock.getDateDerniereCommande() {
        return this.dateDerniereCommande;
    }
    
    public void SuiviStock.setDateDerniereCommande(Date dateDerniereCommande) {
        this.dateDerniereCommande = dateDerniereCommande;
    }
    
    public Date SuiviStock.getDateSuivi() {
        return this.dateSuivi;
    }
    
    public void SuiviStock.setDateSuivi(Date dateSuivi) {
        this.dateSuivi = dateSuivi;
    }
    
}
