// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.domain;

import com.polypharm.gescom.domain.VCDistributeurConcurent;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect VCDistributeurConcurent_Roo_Jpa_Entity {
    
    declare @type: VCDistributeurConcurent: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long VCDistributeurConcurent.id;
    
    @Version
    @Column(name = "version")
    private Integer VCDistributeurConcurent.version;
    
    public Long VCDistributeurConcurent.getId() {
        return this.id;
    }
    
    public void VCDistributeurConcurent.setId(Long id) {
        this.id = id;
    }
    
    public Integer VCDistributeurConcurent.getVersion() {
        return this.version;
    }
    
    public void VCDistributeurConcurent.setVersion(Integer version) {
        this.version = version;
    }
    
}
