// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.domain;

import com.polypharm.gescom.domain.Produit;
import com.polypharm.gescom.domain.VCDistributeurConcurent;
import java.util.Set;

privileged aspect VCDistributeurConcurent_Roo_JavaBean {
    
    public String VCDistributeurConcurent.getNomDistributeur() {
        return this.nomDistributeur;
    }
    
    public void VCDistributeurConcurent.setNomDistributeur(String nomDistributeur) {
        this.nomDistributeur = nomDistributeur;
    }
    
    public String VCDistributeurConcurent.getLocalisation() {
        return this.localisation;
    }
    
    public void VCDistributeurConcurent.setLocalisation(String localisation) {
        this.localisation = localisation;
    }
    
    public Set<Produit> VCDistributeurConcurent.getProduitsDistribues() {
        return this.produitsDistribues;
    }
    
    public void VCDistributeurConcurent.setProduitsDistribues(Set<Produit> produitsDistribues) {
        this.produitsDistribues = produitsDistribues;
    }
    
}
