// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.domain;

import com.polypharm.gescom.domain.VeilleConcurrentielleProduit;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect VeilleConcurrentielleProduit_Roo_Jpa_Entity {
    
    declare @type: VeilleConcurrentielleProduit: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long VeilleConcurrentielleProduit.id;
    
    @Version
    @Column(name = "version")
    private Integer VeilleConcurrentielleProduit.version;
    
    public Long VeilleConcurrentielleProduit.getId() {
        return this.id;
    }
    
    public void VeilleConcurrentielleProduit.setId(Long id) {
        this.id = id;
    }
    
    public Integer VeilleConcurrentielleProduit.getVersion() {
        return this.version;
    }
    
    public void VeilleConcurrentielleProduit.setVersion(Integer version) {
        this.version = version;
    }
    
}
