// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.domain;

import com.polypharm.gescom.domain.Produit;
import com.polypharm.gescom.domain.VeilleConcurrentielleProduit;
import java.math.BigDecimal;

privileged aspect VeilleConcurrentielleProduit_Roo_JavaBean {
    
    public Produit VeilleConcurrentielleProduit.getProduit() {
        return this.produit;
    }
    
    public void VeilleConcurrentielleProduit.setProduit(Produit produit) {
        this.produit = produit;
    }
    
    public BigDecimal VeilleConcurrentielleProduit.getPrixDeVente() {
        return this.prixDeVente;
    }
    
    public void VeilleConcurrentielleProduit.setPrixDeVente(BigDecimal prixDeVente) {
        this.prixDeVente = prixDeVente;
    }
    
    public String VeilleConcurrentielleProduit.getDistributeurPrincipal() {
        return this.distributeurPrincipal;
    }
    
    public void VeilleConcurrentielleProduit.setDistributeurPrincipal(String distributeurPrincipal) {
        this.distributeurPrincipal = distributeurPrincipal;
    }
    
    public BigDecimal VeilleConcurrentielleProduit.getNiveauStockProduitChezConcurent() {
        return this.niveauStockProduitChezConcurent;
    }
    
    public void VeilleConcurrentielleProduit.setNiveauStockProduitChezConcurent(BigDecimal niveauStockProduitChezConcurent) {
        this.niveauStockProduitChezConcurent = niveauStockProduitChezConcurent;
    }
    
}
