// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.domain;

import com.polypharm.gescom.domain.Client;
import com.polypharm.gescom.domain.Personnel;
import com.polypharm.gescom.domain.Produit;
import com.polypharm.gescom.domain.VulgarisationProduit;
import java.util.Date;

privileged aspect VulgarisationProduit_Roo_JavaBean {
    
    public Produit VulgarisationProduit.getProduitVulgarise() {
        return this.produitVulgarise;
    }
    
    public void VulgarisationProduit.setProduitVulgarise(Produit produitVulgarise) {
        this.produitVulgarise = produitVulgarise;
    }
    
    public Client VulgarisationProduit.getClient() {
        return this.client;
    }
    
    public void VulgarisationProduit.setClient(Client client) {
        this.client = client;
    }
    
    public String VulgarisationProduit.getNomInterlocuteur() {
        return this.nomInterlocuteur;
    }
    
    public void VulgarisationProduit.setNomInterlocuteur(String nomInterlocuteur) {
        this.nomInterlocuteur = nomInterlocuteur;
    }
    
    public String VulgarisationProduit.getTelInterlocuteur() {
        return this.telInterlocuteur;
    }
    
    public void VulgarisationProduit.setTelInterlocuteur(String telInterlocuteur) {
        this.telInterlocuteur = telInterlocuteur;
    }
    
    public Date VulgarisationProduit.getDateVulgarisation() {
        return this.dateVulgarisation;
    }
    
    public void VulgarisationProduit.setDateVulgarisation(Date dateVulgarisation) {
        this.dateVulgarisation = dateVulgarisation;
    }
    
    public Personnel VulgarisationProduit.getAuteur() {
        return this.auteur;
    }
    
    public void VulgarisationProduit.setAuteur(Personnel auteur) {
        this.auteur = auteur;
    }
    
}
