// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.domain;

import com.polypharm.gescom.domain.VulgarisationProduit;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect VulgarisationProduit_Roo_Jpa_Entity {
    
    declare @type: VulgarisationProduit: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long VulgarisationProduit.id;
    
    @Version
    @Column(name = "version")
    private Integer VulgarisationProduit.version;
    
    public Long VulgarisationProduit.getId() {
        return this.id;
    }
    
    public void VulgarisationProduit.setId(Long id) {
        this.id = id;
    }
    
    public Integer VulgarisationProduit.getVersion() {
        return this.version;
    }
    
    public void VulgarisationProduit.setVersion(Integer version) {
        this.version = version;
    }
    
}
