// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.domain;

import com.polypharm.gescom.domain.VulgarisationProduit;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect VulgarisationProduit_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager VulgarisationProduit.entityManager;
    
    public static final EntityManager VulgarisationProduit.entityManager() {
        EntityManager em = new VulgarisationProduit().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long VulgarisationProduit.countVulgarisationProduits() {
        return entityManager().createQuery("SELECT COUNT(o) FROM VulgarisationProduit o", Long.class).getSingleResult();
    }
    
    public static List<VulgarisationProduit> VulgarisationProduit.findAllVulgarisationProduits() {
        return entityManager().createQuery("SELECT o FROM VulgarisationProduit o", VulgarisationProduit.class).getResultList();
    }
    
    public static VulgarisationProduit VulgarisationProduit.findVulgarisationProduit(Long id) {
        if (id == null) return null;
        return entityManager().find(VulgarisationProduit.class, id);
    }
    
    public static List<VulgarisationProduit> VulgarisationProduit.findVulgarisationProduitEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM VulgarisationProduit o", VulgarisationProduit.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void VulgarisationProduit.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void VulgarisationProduit.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            VulgarisationProduit attached = VulgarisationProduit.findVulgarisationProduit(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void VulgarisationProduit.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void VulgarisationProduit.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public VulgarisationProduit VulgarisationProduit.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        VulgarisationProduit merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
