// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.web;

import com.polypharm.gescom.domain.Agence;
import com.polypharm.gescom.service.AgenceService;
import com.polypharm.gescom.web.AgenceController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect AgenceController_Roo_Controller {
    
    @Autowired
    AgenceService AgenceController.agenceService;
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String AgenceController.create(@Valid Agence agence, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, agence);
            return "agences/create";
        }
        uiModel.asMap().clear();
        agenceService.saveAgence(agence);
        return "redirect:/agences/" + encodeUrlPathSegment(agence.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String AgenceController.createForm(Model uiModel) {
        populateEditForm(uiModel, new Agence());
        return "agences/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String AgenceController.show(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("agence", agenceService.findAgence(id));
        uiModel.addAttribute("itemId", id);
        return "agences/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String AgenceController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("agences", agenceService.findAgenceEntries(firstResult, sizeNo));
            float nrOfPages = (float) agenceService.countAllAgences() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("agences", agenceService.findAllAgences());
        }
        return "agences/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String AgenceController.update(@Valid Agence agence, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, agence);
            return "agences/update";
        }
        uiModel.asMap().clear();
        agenceService.updateAgence(agence);
        return "redirect:/agences/" + encodeUrlPathSegment(agence.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String AgenceController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        populateEditForm(uiModel, agenceService.findAgence(id));
        return "agences/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String AgenceController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        Agence agence = agenceService.findAgence(id);
        agenceService.deleteAgence(agence);
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/agences";
    }
    
    void AgenceController.populateEditForm(Model uiModel, Agence agence) {
        uiModel.addAttribute("agence", agence);
    }
    
    String AgenceController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
