// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.web;

import com.polypharm.gescom.domain.Client;
import com.polypharm.gescom.service.ClientService;
import com.polypharm.gescom.web.ClientController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.joda.time.format.DateTimeFormat;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.i18n.LocaleContextHolder;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect ClientController_Roo_Controller {
    
    @Autowired
    ClientService ClientController.clientService;
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String ClientController.create(@Valid Client client, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, client);
            return "clients/create";
        }
        uiModel.asMap().clear();
        clientService.saveClient(client);
        return "redirect:/clients/" + encodeUrlPathSegment(client.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String ClientController.createForm(Model uiModel) {
        populateEditForm(uiModel, new Client());
        return "clients/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String ClientController.show(@PathVariable("id") Long id, Model uiModel) {
        addDateTimeFormatPatterns(uiModel);
        uiModel.addAttribute("client", clientService.findClient(id));
        uiModel.addAttribute("itemId", id);
        return "clients/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String ClientController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, @RequestParam(value = "sortFieldName", required = false) String sortFieldName, @RequestParam(value = "sortOrder", required = false) String sortOrder, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("clients", clientService.findClientEntries(firstResult, sizeNo));
            float nrOfPages = (float) clientService.countAllClients() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("clients", clientService.findAllClients());
        }
        addDateTimeFormatPatterns(uiModel);
        return "clients/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String ClientController.update(@Valid Client client, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, client);
            return "clients/update";
        }
        uiModel.asMap().clear();
        clientService.updateClient(client);
        return "redirect:/clients/" + encodeUrlPathSegment(client.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String ClientController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        populateEditForm(uiModel, clientService.findClient(id));
        return "clients/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String ClientController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        Client client = clientService.findClient(id);
        clientService.deleteClient(client);
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/clients";
    }
    
    void ClientController.addDateTimeFormatPatterns(Model uiModel) {
        uiModel.addAttribute("client_expirationcartecontribuable_date_format", DateTimeFormat.patternForStyle("M-", LocaleContextHolder.getLocale()));
        uiModel.addAttribute("client_expirationpatente_date_format", DateTimeFormat.patternForStyle("M-", LocaleContextHolder.getLocale()));
    }
    
    void ClientController.populateEditForm(Model uiModel, Client client) {
        uiModel.addAttribute("client", client);
        addDateTimeFormatPatterns(uiModel);
    }
    
    String ClientController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
