// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.web;

import com.polypharm.gescom.domain.DossierCreance;
import com.polypharm.gescom.service.ClientService;
import com.polypharm.gescom.service.DossierCreanceService;
import com.polypharm.gescom.service.PersonnelService;
import com.polypharm.gescom.web.DossierCreanceController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.joda.time.format.DateTimeFormat;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.i18n.LocaleContextHolder;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect DossierCreanceController_Roo_Controller {
    
    @Autowired
    DossierCreanceService DossierCreanceController.dossierCreanceService;
    
    @Autowired
    ClientService DossierCreanceController.clientService;
    
    @Autowired
    PersonnelService DossierCreanceController.personnelService;
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String DossierCreanceController.create(@Valid DossierCreance dossierCreance, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, dossierCreance);
            return "dossiercreances/create";
        }
        uiModel.asMap().clear();
        dossierCreanceService.saveDossierCreance(dossierCreance);
        return "redirect:/dossiercreances/" + encodeUrlPathSegment(dossierCreance.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String DossierCreanceController.createForm(Model uiModel) {
        populateEditForm(uiModel, new DossierCreance());
        return "dossiercreances/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String DossierCreanceController.show(@PathVariable("id") Long id, Model uiModel) {
        addDateTimeFormatPatterns(uiModel);
        uiModel.addAttribute("dossiercreance", dossierCreanceService.findDossierCreance(id));
        uiModel.addAttribute("itemId", id);
        return "dossiercreances/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String DossierCreanceController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, @RequestParam(value = "sortFieldName", required = false) String sortFieldName, @RequestParam(value = "sortOrder", required = false) String sortOrder, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("dossiercreances", DossierCreance.findDossierCreanceEntries(firstResult, sizeNo, sortFieldName, sortOrder));
            float nrOfPages = (float) dossierCreanceService.countAllDossierCreances() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("dossiercreances", DossierCreance.findAllDossierCreances(sortFieldName, sortOrder));
        }
        addDateTimeFormatPatterns(uiModel);
        return "dossiercreances/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String DossierCreanceController.update(@Valid DossierCreance dossierCreance, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, dossierCreance);
            return "dossiercreances/update";
        }
        uiModel.asMap().clear();
        dossierCreanceService.updateDossierCreance(dossierCreance);
        return "redirect:/dossiercreances/" + encodeUrlPathSegment(dossierCreance.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String DossierCreanceController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        populateEditForm(uiModel, dossierCreanceService.findDossierCreance(id));
        return "dossiercreances/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String DossierCreanceController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        DossierCreance dossierCreance = dossierCreanceService.findDossierCreance(id);
        dossierCreanceService.deleteDossierCreance(dossierCreance);
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/dossiercreances";
    }
    
    void DossierCreanceController.addDateTimeFormatPatterns(Model uiModel) {
        uiModel.addAttribute("dossierCreance_dateemission_date_format", DateTimeFormat.patternForStyle("M-", LocaleContextHolder.getLocale()));
        uiModel.addAttribute("dossierCreance_dateechance_date_format", DateTimeFormat.patternForStyle("M-", LocaleContextHolder.getLocale()));
    }
    
    void DossierCreanceController.populateEditForm(Model uiModel, DossierCreance dossierCreance) {
        uiModel.addAttribute("dossierCreance", dossierCreance);
        addDateTimeFormatPatterns(uiModel);
        uiModel.addAttribute("clients", clientService.findAllClients());
        uiModel.addAttribute("personnels", personnelService.findAllPersonnels());
    }
    
    String DossierCreanceController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
