// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.web;

import com.polypharm.gescom.domain.FamilleProduit;
import com.polypharm.gescom.service.FamilleProduitService;
import com.polypharm.gescom.web.FamilleProduitController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect FamilleProduitController_Roo_Controller {
    
    @Autowired
    FamilleProduitService FamilleProduitController.familleProduitService;
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String FamilleProduitController.create(@Valid FamilleProduit familleProduit, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, familleProduit);
            return "familleproduits/create";
        }
        uiModel.asMap().clear();
        familleProduitService.saveFamilleProduit(familleProduit);
        return "redirect:/familleproduits/" + encodeUrlPathSegment(familleProduit.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String FamilleProduitController.createForm(Model uiModel) {
        populateEditForm(uiModel, new FamilleProduit());
        return "familleproduits/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String FamilleProduitController.show(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("familleproduit", familleProduitService.findFamilleProduit(id));
        uiModel.addAttribute("itemId", id);
        return "familleproduits/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String FamilleProduitController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("familleproduits", familleProduitService.findFamilleProduitEntries(firstResult, sizeNo));
            float nrOfPages = (float) familleProduitService.countAllFamilleProduits() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("familleproduits", familleProduitService.findAllFamilleProduits());
        }
        return "familleproduits/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String FamilleProduitController.update(@Valid FamilleProduit familleProduit, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, familleProduit);
            return "familleproduits/update";
        }
        uiModel.asMap().clear();
        familleProduitService.updateFamilleProduit(familleProduit);
        return "redirect:/familleproduits/" + encodeUrlPathSegment(familleProduit.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String FamilleProduitController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        populateEditForm(uiModel, familleProduitService.findFamilleProduit(id));
        return "familleproduits/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String FamilleProduitController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        FamilleProduit familleProduit = familleProduitService.findFamilleProduit(id);
        familleProduitService.deleteFamilleProduit(familleProduit);
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/familleproduits";
    }
    
    void FamilleProduitController.populateEditForm(Model uiModel, FamilleProduit familleProduit) {
        uiModel.addAttribute("familleProduit", familleProduit);
    }
    
    String FamilleProduitController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
