// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.web;

import com.polypharm.gescom.domain.FormationUtilisateur;
import com.polypharm.gescom.service.FormationUtilisateurService;
import com.polypharm.gescom.web.FormationUtilisateurController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.joda.time.format.DateTimeFormat;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.i18n.LocaleContextHolder;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect FormationUtilisateurController_Roo_Controller {
    
    @Autowired
    FormationUtilisateurService FormationUtilisateurController.formationUtilisateurService;
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String FormationUtilisateurController.create(@Valid FormationUtilisateur formationUtilisateur, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, formationUtilisateur);
            return "formationutilisateurs/create";
        }
        uiModel.asMap().clear();
        formationUtilisateurService.saveFormationUtilisateur(formationUtilisateur);
        return "redirect:/formationutilisateurs/" + encodeUrlPathSegment(formationUtilisateur.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String FormationUtilisateurController.createForm(Model uiModel) {
        populateEditForm(uiModel, new FormationUtilisateur());
        return "formationutilisateurs/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String FormationUtilisateurController.show(@PathVariable("id") Long id, Model uiModel) {
        addDateTimeFormatPatterns(uiModel);
        uiModel.addAttribute("formationutilisateur", formationUtilisateurService.findFormationUtilisateur(id));
        uiModel.addAttribute("itemId", id);
        return "formationutilisateurs/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String FormationUtilisateurController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, @RequestParam(value = "sortFieldName", required = false) String sortFieldName, @RequestParam(value = "sortOrder", required = false) String sortOrder, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("formationutilisateurs", FormationUtilisateur.findFormationUtilisateurEntries(firstResult, sizeNo, sortFieldName, sortOrder));
            float nrOfPages = (float) formationUtilisateurService.countAllFormationUtilisateurs() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("formationutilisateurs", FormationUtilisateur.findAllFormationUtilisateurs(sortFieldName, sortOrder));
        }
        addDateTimeFormatPatterns(uiModel);
        return "formationutilisateurs/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String FormationUtilisateurController.update(@Valid FormationUtilisateur formationUtilisateur, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, formationUtilisateur);
            return "formationutilisateurs/update";
        }
        uiModel.asMap().clear();
        formationUtilisateurService.updateFormationUtilisateur(formationUtilisateur);
        return "redirect:/formationutilisateurs/" + encodeUrlPathSegment(formationUtilisateur.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String FormationUtilisateurController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        populateEditForm(uiModel, formationUtilisateurService.findFormationUtilisateur(id));
        return "formationutilisateurs/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String FormationUtilisateurController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        FormationUtilisateur formationUtilisateur = formationUtilisateurService.findFormationUtilisateur(id);
        formationUtilisateurService.deleteFormationUtilisateur(formationUtilisateur);
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/formationutilisateurs";
    }
    
    void FormationUtilisateurController.addDateTimeFormatPatterns(Model uiModel) {
        uiModel.addAttribute("formationUtilisateur_dateformation_date_format", DateTimeFormat.patternForStyle("M-", LocaleContextHolder.getLocale()));
    }
    
    void FormationUtilisateurController.populateEditForm(Model uiModel, FormationUtilisateur formationUtilisateur) {
        uiModel.addAttribute("formationUtilisateur", formationUtilisateur);
        addDateTimeFormatPatterns(uiModel);
    }
    
    String FormationUtilisateurController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
