// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.web;

import com.polypharm.gescom.domain.Livraison;
import com.polypharm.gescom.service.ClientService;
import com.polypharm.gescom.service.LivraisonService;
import com.polypharm.gescom.web.LivraisonController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect LivraisonController_Roo_Controller {
    
    @Autowired
    LivraisonService LivraisonController.livraisonService;
    
    @Autowired
    ClientService LivraisonController.clientService;
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String LivraisonController.create(@Valid Livraison livraison, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, livraison);
            return "livraisons/create";
        }
        uiModel.asMap().clear();
        livraisonService.saveLivraison(livraison);
        return "redirect:/livraisons/" + encodeUrlPathSegment(livraison.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String LivraisonController.createForm(Model uiModel) {
        populateEditForm(uiModel, new Livraison());
        return "livraisons/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String LivraisonController.show(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("livraison", livraisonService.findLivraison(id));
        uiModel.addAttribute("itemId", id);
        return "livraisons/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String LivraisonController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, @RequestParam(value = "sortFieldName", required = false) String sortFieldName, @RequestParam(value = "sortOrder", required = false) String sortOrder, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("livraisons", Livraison.findLivraisonEntries(firstResult, sizeNo, sortFieldName, sortOrder));
            float nrOfPages = (float) livraisonService.countAllLivraisons() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("livraisons", Livraison.findAllLivraisons(sortFieldName, sortOrder));
        }
        return "livraisons/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String LivraisonController.update(@Valid Livraison livraison, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, livraison);
            return "livraisons/update";
        }
        uiModel.asMap().clear();
        livraisonService.updateLivraison(livraison);
        return "redirect:/livraisons/" + encodeUrlPathSegment(livraison.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String LivraisonController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        populateEditForm(uiModel, livraisonService.findLivraison(id));
        return "livraisons/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String LivraisonController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        Livraison livraison = livraisonService.findLivraison(id);
        livraisonService.deleteLivraison(livraison);
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/livraisons";
    }
    
    void LivraisonController.populateEditForm(Model uiModel, Livraison livraison) {
        uiModel.addAttribute("livraison", livraison);
        uiModel.addAttribute("clients", clientService.findAllClients());
    }
    
    String LivraisonController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
