// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.web;

import com.polypharm.gescom.domain.Produit;
import com.polypharm.gescom.service.FamilleProduitService;
import com.polypharm.gescom.service.ProduitService;
import com.polypharm.gescom.web.ProduitController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect ProduitController_Roo_Controller {
    
    @Autowired
    ProduitService ProduitController.produitService;
    
    @Autowired
    FamilleProduitService ProduitController.familleProduitService;
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String ProduitController.create(@Valid Produit produit, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, produit);
            return "produits/create";
        }
        uiModel.asMap().clear();
        produitService.saveProduit(produit);
        return "redirect:/produits/" + encodeUrlPathSegment(produit.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String ProduitController.createForm(Model uiModel) {
        populateEditForm(uiModel, new Produit());
        return "produits/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String ProduitController.show(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("produit", produitService.findProduit(id));
        uiModel.addAttribute("itemId", id);
        return "produits/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String ProduitController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("produits", produitService.findProduitEntries(firstResult, sizeNo));
            float nrOfPages = (float) produitService.countAllProduits() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("produits", produitService.findAllProduits());
        }
        return "produits/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String ProduitController.update(@Valid Produit produit, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, produit);
            return "produits/update";
        }
        uiModel.asMap().clear();
        produitService.updateProduit(produit);
        return "redirect:/produits/" + encodeUrlPathSegment(produit.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String ProduitController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        populateEditForm(uiModel, produitService.findProduit(id));
        return "produits/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String ProduitController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        Produit produit = produitService.findProduit(id);
        produitService.deleteProduit(produit);
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/produits";
    }
    
    void ProduitController.populateEditForm(Model uiModel, Produit produit) {
        uiModel.addAttribute("produit", produit);
        uiModel.addAttribute("familleproduits", familleProduitService.findAllFamilleProduits());
    }
    
    String ProduitController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
