// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.web;

import com.polypharm.gescom.domain.ProjetCommande;
import com.polypharm.gescom.service.ClientService;
import com.polypharm.gescom.service.ProjetCommandeService;
import com.polypharm.gescom.web.ProjetCommandeController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect ProjetCommandeController_Roo_Controller {
    
    @Autowired
    ProjetCommandeService ProjetCommandeController.projetCommandeService;
    
    @Autowired
    ClientService ProjetCommandeController.clientService;
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String ProjetCommandeController.create(@Valid ProjetCommande projetCommande, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, projetCommande);
            return "projetcommandes/create";
        }
        uiModel.asMap().clear();
        projetCommandeService.saveProjetCommande(projetCommande);
        return "redirect:/projetcommandes/" + encodeUrlPathSegment(projetCommande.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String ProjetCommandeController.createForm(Model uiModel) {
        populateEditForm(uiModel, new ProjetCommande());
        return "projetcommandes/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String ProjetCommandeController.show(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("projetcommande", projetCommandeService.findProjetCommande(id));
        uiModel.addAttribute("itemId", id);
        return "projetcommandes/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String ProjetCommandeController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("projetcommandes", projetCommandeService.findProjetCommandeEntries(firstResult, sizeNo));
            float nrOfPages = (float) projetCommandeService.countAllProjetCommandes() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("projetcommandes", projetCommandeService.findAllProjetCommandes());
        }
        return "projetcommandes/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String ProjetCommandeController.update(@Valid ProjetCommande projetCommande, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, projetCommande);
            return "projetcommandes/update";
        }
        uiModel.asMap().clear();
        projetCommandeService.updateProjetCommande(projetCommande);
        return "redirect:/projetcommandes/" + encodeUrlPathSegment(projetCommande.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String ProjetCommandeController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        populateEditForm(uiModel, projetCommandeService.findProjetCommande(id));
        return "projetcommandes/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String ProjetCommandeController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        ProjetCommande projetCommande = projetCommandeService.findProjetCommande(id);
        projetCommandeService.deleteProjetCommande(projetCommande);
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/projetcommandes";
    }
    
    void ProjetCommandeController.populateEditForm(Model uiModel, ProjetCommande projetCommande) {
        uiModel.addAttribute("projetCommande", projetCommande);
        uiModel.addAttribute("clients", clientService.findAllClients());
    }
    
    String ProjetCommandeController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
