// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.polypharm.gescom.web;

import com.polypharm.gescom.domain.VeilleConcurrentielleProduit;
import com.polypharm.gescom.service.ProduitService;
import com.polypharm.gescom.service.VeilleConcurrentielleProduitService;
import com.polypharm.gescom.web.VeilleConcurrentielleProduitController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect VeilleConcurrentielleProduitController_Roo_Controller {
    
    @Autowired
    VeilleConcurrentielleProduitService VeilleConcurrentielleProduitController.veilleConcurrentielleProduitService;
    
    @Autowired
    ProduitService VeilleConcurrentielleProduitController.produitService;
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String VeilleConcurrentielleProduitController.create(@Valid VeilleConcurrentielleProduit veilleConcurrentielleProduit, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, veilleConcurrentielleProduit);
            return "veilleconcurrentielleproduits/create";
        }
        uiModel.asMap().clear();
        veilleConcurrentielleProduitService.saveVeilleConcurrentielleProduit(veilleConcurrentielleProduit);
        return "redirect:/veilleconcurrentielleproduits/" + encodeUrlPathSegment(veilleConcurrentielleProduit.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String VeilleConcurrentielleProduitController.createForm(Model uiModel) {
        populateEditForm(uiModel, new VeilleConcurrentielleProduit());
        return "veilleconcurrentielleproduits/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String VeilleConcurrentielleProduitController.show(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("veilleconcurrentielleproduit", veilleConcurrentielleProduitService.findVeilleConcurrentielleProduit(id));
        uiModel.addAttribute("itemId", id);
        return "veilleconcurrentielleproduits/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String VeilleConcurrentielleProduitController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, @RequestParam(value = "sortFieldName", required = false) String sortFieldName, @RequestParam(value = "sortOrder", required = false) String sortOrder, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("veilleconcurrentielleproduits", VeilleConcurrentielleProduit.findVeilleConcurrentielleProduitEntries(firstResult, sizeNo, sortFieldName, sortOrder));
            float nrOfPages = (float) veilleConcurrentielleProduitService.countAllVeilleConcurrentielleProduits() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("veilleconcurrentielleproduits", VeilleConcurrentielleProduit.findAllVeilleConcurrentielleProduits(sortFieldName, sortOrder));
        }
        return "veilleconcurrentielleproduits/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String VeilleConcurrentielleProduitController.update(@Valid VeilleConcurrentielleProduit veilleConcurrentielleProduit, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, veilleConcurrentielleProduit);
            return "veilleconcurrentielleproduits/update";
        }
        uiModel.asMap().clear();
        veilleConcurrentielleProduitService.updateVeilleConcurrentielleProduit(veilleConcurrentielleProduit);
        return "redirect:/veilleconcurrentielleproduits/" + encodeUrlPathSegment(veilleConcurrentielleProduit.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String VeilleConcurrentielleProduitController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        populateEditForm(uiModel, veilleConcurrentielleProduitService.findVeilleConcurrentielleProduit(id));
        return "veilleconcurrentielleproduits/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String VeilleConcurrentielleProduitController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        VeilleConcurrentielleProduit veilleConcurrentielleProduit = veilleConcurrentielleProduitService.findVeilleConcurrentielleProduit(id);
        veilleConcurrentielleProduitService.deleteVeilleConcurrentielleProduit(veilleConcurrentielleProduit);
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/veilleconcurrentielleproduits";
    }
    
    void VeilleConcurrentielleProduitController.populateEditForm(Model uiModel, VeilleConcurrentielleProduit veilleConcurrentielleProduit) {
        uiModel.addAttribute("veilleConcurrentielleProduit", veilleConcurrentielleProduit);
        uiModel.addAttribute("produits", produitService.findAllProduits());
    }
    
    String VeilleConcurrentielleProduitController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
